"""The Mimeo Configuration Constants module."""

# The Mimeo output details configuration
OUTPUT_KEY = "output"
OUTPUT_DIRECTION_KEY = "direction"
OUTPUT_FORMAT_KEY = "format"
OUTPUT_XML_DECLARATION_KEY = "xml_declaration"
OUTPUT_INDENT_KEY = "indent"
OUTPUT_DIRECTORY_PATH_KEY = "directory_path"
OUTPUT_FILE_NAME_KEY = "file_name"
OUTPUT_METHOD_KEY = "method"
OUTPUT_PROTOCOL_KEY = "protocol"
OUTPUT_HOST_KEY = "host"
OUTPUT_PORT_KEY = "port"
OUTPUT_ENDPOINT_KEY = "endpoint"
OUTPUT_USERNAME_KEY = "username"
OUTPUT_PASSWORD_KEY = "password"

# The Mimeo Vars' configuration
VARS_KEY = "vars"

# The Mimeo Templates' configuration
TEMPLATES_KEY = "_templates_"
TEMPLATES_COUNT_KEY = "count"
TEMPLATES_MODEL_KEY = "model"

# The Mimeo Models' configuration
MODEL_CONTEXT_KEY = "context"
MODEL_ATTRIBUTES_KEY = "_attrs"
MODEL_VALUE_KEY = "_value"
MODEL_MIMEO_UTIL_KEY = "_mimeo_util"
MODEL_MIMEO_UTIL_NAME_KEY = "_name"

# The Mimeo output format values
OUTPUT_FORMAT_XML = "xml"
SUPPORTED_OUTPUT_FORMATS = (
    OUTPUT_FORMAT_XML,)

# The Mimeo output direction values
OUTPUT_DIRECTION_FILE = "file"
OUTPUT_DIRECTION_STD_OUT = "stdout"
OUTPUT_DIRECTION_HTTP = "http"
SUPPORTED_OUTPUT_DIRECTIONS = (
    OUTPUT_DIRECTION_STD_OUT,
    OUTPUT_DIRECTION_FILE,
    OUTPUT_DIRECTION_HTTP)

# The Mimeo output HTTP request methods
OUTPUT_DIRECTION_HTTP_REQUEST_POST = "POST"
OUTPUT_DIRECTION_HTTP_REQUEST_PUT = "PUT"
SUPPORTED_REQUEST_METHODS = (
    OUTPUT_DIRECTION_HTTP_REQUEST_POST,
    OUTPUT_DIRECTION_HTTP_REQUEST_PUT)

# The Mimeo output HTTP protocols
OUTPUT_DIRECTION_HTTP_PROTOCOL_HTTP = "http"
OUTPUT_DIRECTION_HTTP_PROTOCOL_HTTPS = "https"
SUPPORTED_REQUEST_PROTOCOLS = (
    OUTPUT_DIRECTION_HTTP_PROTOCOL_HTTP,
    OUTPUT_DIRECTION_HTTP_PROTOCOL_HTTPS)


# The Mimeo HTTP output required details
REQUIRED_HTTP_DETAILS = (
    OUTPUT_HOST_KEY,
    OUTPUT_ENDPOINT_KEY,
    OUTPUT_USERNAME_KEY,
    OUTPUT_PASSWORD_KEY)

__all__ = [
    "OUTPUT_KEY",
    "OUTPUT_DIRECTION_KEY",
    "OUTPUT_FORMAT_KEY",
    "OUTPUT_XML_DECLARATION_KEY",
    "OUTPUT_INDENT_KEY",
    "OUTPUT_DIRECTORY_PATH_KEY",
    "OUTPUT_FILE_NAME_KEY",
    "OUTPUT_METHOD_KEY",
    "OUTPUT_PROTOCOL_KEY",
    "OUTPUT_HOST_KEY",
    "OUTPUT_PORT_KEY",
    "OUTPUT_ENDPOINT_KEY",
    "OUTPUT_USERNAME_KEY",
    "OUTPUT_PASSWORD_KEY",
    "VARS_KEY",
    "TEMPLATES_KEY",
    "TEMPLATES_COUNT_KEY",
    "TEMPLATES_MODEL_KEY",
    "MODEL_CONTEXT_KEY",
    "MODEL_ATTRIBUTES_KEY",
    "MODEL_VALUE_KEY",
    "MODEL_MIMEO_UTIL_KEY",
    "MODEL_MIMEO_UTIL_NAME_KEY",
    "OUTPUT_FORMAT_XML",
    "SUPPORTED_OUTPUT_FORMATS",
    "OUTPUT_DIRECTION_FILE",
    "OUTPUT_DIRECTION_STD_OUT",
    "OUTPUT_DIRECTION_HTTP",
    "SUPPORTED_OUTPUT_DIRECTIONS",
    "OUTPUT_DIRECTION_HTTP_REQUEST_POST",
    "OUTPUT_DIRECTION_HTTP_REQUEST_PUT",
    "SUPPORTED_REQUEST_METHODS",
    "OUTPUT_DIRECTION_HTTP_PROTOCOL_HTTP",
    "OUTPUT_DIRECTION_HTTP_PROTOCOL_HTTPS",
    "SUPPORTED_REQUEST_PROTOCOLS",
    "REQUIRED_HTTP_DETAILS",
]
