version: 1

formatters:
  info:
    format: '%(message)s'
  debug:
    format: '[%(name)s %(module)s.%(funcName)s:%(lineno)d] %(levelname)s: %(message)s'

filters:
  infoFilter:
    (): mimeo.logging.InfoFilter
  debugFilter:
    (): mimeo.logging.DebugFilter

handlers:
  info:
    class: logging.StreamHandler
    level: INFO
    formatter: info
    filters: [infoFilter]
    stream: ext://sys.stdout
  debug:
    class: logging.StreamHandler
    level: DEBUG
    formatter: debug
    filters: [debugFilter]
    stream: ext://sys.stdout

loggers:
  mimeo:
    level: DEBUG
    handlers: [info, debug]
    propagate: no

root:
  level: WARNING
  handlers: [info]
