name: Update a code coverage badge

on: [pull_request]
#  push:
#    branches:
#      - main
jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install pip-tools
          pip-compile --extra test pyproject.toml
          pip install -r requirements.txt

      - name: Build mimeo
        run: pip install -e .

      - name: Create test report
        run: |
          pytest --cov=src tests | tee output.txt

      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: output.txt

      - name: Update README with Code Coverage Badge
        run: |
          sed -i -e "s/Code%20Coverage-[0-9]*%25-[a-z]*/Code%20Coverage-${{ steps.coverageComment.outputs.coverage }}%25-${{ steps.coverageComment.outputs.color }}/g" ./README.md
          rm output.txt

      - name: Set git config before push
        run: git config --local --unset-all "http.https://github.com/.extraheader"

      - name: Commit & Push changes to README
        uses: actions-js/push@master
        with:
          message: Update code coverage badge on README
          branch: "feature/mimeo-99"
          github_token: ${{ secrets.GITHUB_TOKEN }}
