name: Create a coverage report

on: [pull_request]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install pip-tools
          pip-compile --extra test pyproject.toml
          pip install -r requirements.txt
      - name: Build mimeo
        run: pip install .
      - name: Create a coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=xml:coverage.xml --cov=src tests/
      - name: Put a pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          title: Code Coverage Report
          badge-title: Code Coverage
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
          junitxml-title: Summary
