name: Lint Mimeo

on:
  pull_request:
  push:
    branches:
      - develop
jobs:
  test-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install pip-tools
          pip-compile --extra dev pyproject.toml
          pip install -r requirements.txt
      - name: Lint with Ruff
        run: ruff --format=github .
